<a href="https://colab.research.google.com/github/Prateek-Datascientist/16th-Jan-2024/blob/main/1_Feb_2024_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('/content/bigmart.csv')

In [26]:

a =df.corr()
a

<ipython-input-26-7a5ee5329413>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  a =df.corr()


Item_Weight  Item_Visibility  Item_MRP  \
Item_Weight                   1.000000        -0.014048  0.027141   
Item_Visibility              -0.014048         1.000000 -0.001315   
Item_MRP                      0.027141        -0.001315  1.000000   
Outlet_Establishment_Year    -0.011588        -0.074834  0.005020   
Item_Outlet_Sales             0.014123        -0.128625  0.567574   

                           Outlet_Establishment_Year  Item_Outlet_Sales  
Item_Weight                                -0.011588           0.014123  
Item_Visibility                            -0.074834          -0.128625  
Item_MRP                                    0.005020           0.567574  
Outlet_Establishment_Year                   1.000000          -0.049135  
Item_Outlet_Sales                          -0.049135           1.000000

In [27]:
a_val = a.values
a_index = a.index
a_col = a.columns
l = []
for i in range(len(a_val)):
  for j in range(len(a_val)):
    if a_val[i][j] > 0.8:
      l.append([a_index[i] , a_col[j], a_val[i][j]])
for i in l:
  print(i)

['Item_Weight', 'Item_Weight', 1.0]
['Item_Visibility', 'Item_Visibility', 1.0]
['Item_MRP', 'Item_MRP', 1.0]
['Outlet_Establishment_Year', 'Outlet_Establishment_Year', 1.0]
['Item_Outlet_Sales', 'Item_Outlet_Sales', 1.0]


In [32]:
df.info()
a = df.select_dtypes(include= 'float')


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                6113 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [33]:
a.columns

Index(['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Item_Outlet_Sales'], dtype='object')

In [40]:
a1 = a.filter([ 'Item_Visibility', 'Item_MRP'])
a = a.filter([ 'Item_Visibility', 'Item_MRP' , 'Item_Outlet_Sales'])

# Backward Feature Elimination / Recursive Feature Elimination

In [37]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [41]:
a.isna().sum()

Item_Visibility      0
Item_MRP             0
Item_Outlet_Sales    0
dtype: int64

In [42]:
rfe_var = RFE(estimator = LinearRegression(),  n_features_to_select= 3, step=1)
rfe = rfe_var.fit(a1, a['Item_Outlet_Sales'] )


In [44]:
rfe.support_

array([ True,  True])

In [45]:
rfe.ranking_

array([1, 1])

In [46]:
rfe1 = rfe_var.fit_transform(a1, a['Item_Outlet_Sales'])

In [67]:
rfe1
a = rfe1.max()
rfe1

array([[1.60473010e-02, 2.49809200e+02],
       [1.92782160e-02, 4.82692000e+01],
       [1.67600750e-02, 1.41618000e+02],
       ...,
       [3.51862710e-02, 8.51224000e+01],
       [1.45220646e-01, 1.03133200e+02],
       [4.48782800e-02, 7.54670000e+01]])

In [49]:
print(type(rfe1))
print(type(rfe))

<class 'numpy.ndarray'>
<class 'sklearn.feature_selection._rfe.RFE'>


# New Feature Creation

In [62]:
a = df.Item_Outlet_Sales
a1 = pd.cut( [1,2,3,4,5,6,7,8,9,1,2,3,4,45,7,65,4,32,3] , bins = 4 , labels= ['Poor' ,'Mid' , 'Good' ,'Excellent'])
#df.head(25)

poor = 0
mid = 0
good = 0
for i in a1:
  if i == "Poor":
    poor += 1
  if i == 'Mid':
    mid += 1
  if i == 'Good':
    good += 1
print(poor)
print(mid)
print(good)
for i in a1:
  print(i , end = ' ')


16
1
1
Poor Poor Poor Poor Poor Poor Poor Poor Poor Poor Poor Poor Poor Good Poor Excellent Poor Mid Poor 

In [87]:
df = pd.read_csv('/content/startup.csv')

In [88]:
df1 = df.filter(df.columns[0 : (len(df.columns)-1 ) ], axis =1  )
print(df1.isna().sum()*100/len(df1))

R&D Spend           0.0
Administration      0.0
Advertisment       72.0
Marketing Spend     0.0
dtype: float64


In [74]:
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

In [81]:
rfe1 = rfe_var.fit_transform(df1 ,df['Profit'] )

In [83]:
print(type(rfe))
print(rfe)
print()

print(type(rfe1))
print(rfe1[0:3])

<class 'sklearn.feature_selection._rfe.RFE'>
RFE(estimator=LinearRegression(), n_features_to_select=2)

<class 'numpy.ndarray'>
[[165349.2  471784.1 ]
 [162597.7  443898.53]
 [153441.51 407934.54]]


In [96]:
rfe_var = RFE(estimator = LinearRegression(),  n_features_to_select=4, step=50)
rfe = rfe_var.fit(df1.fillna(0) ,df['Profit'] )
rfe.support_

array([ True,  True,  True,  True])